---
title: "Repeated Measures"
author: "Nikam Vikrant"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
r_Data=read.csv("C:/Users/vikra/Downloads/DBP DATA.csv")
head(r_Data,3)
library(ggplot2)
boxplot(r_Data[,3:7],xlab="Visits",ylab="Blood Pressure",main='Comparisons of repeared measures of diastolic  blood pressure ')

```

```{r}
r_Data$diff=rep(0,40)
r_Data$diff=r_Data$DBP5-r_Data$DBP1

r_Data$diff

t.test(diff~TRT,data=r_Data,var.equal=T)

#Welch T-test

t.test(diff~TRT,data=r_Data)
```

```{r}
ggplot(r_Data,aes(diff,group=TRT,col=TRT))+geom_boxplot()

```
```{r}
boxplot(diff~TRT,data=r_Data)
```
```{r}
r_data2=data.frame("bp"=c(r_Data[,3],r_Data[,4],r_Data[,5],r_Data[,6],r_Data[,7]),"TRT"=rep(c(rep(c("A","B"),each=20)),5),"Visits"=rep(1:5,each=40))
r_data2

```

```{r}
r_data2$TRT=as.factor(r_data2$TRT)
r_data2$Visits=as.factor(r_data2$Visits)
```

```{r}
M1=aov(bp~TRT+Visits+TRT*Visits,data=r_data2)
summary(M1)
```





```{r}
Y=cbind(r_Data$DBPl,r_Data$DBP2,r_Data$DBP3,r_Data$DBP4,r_Data$DBP5)
manova(Y~TRT,data=r_Data)
```

```{r}
summary(manova(Y~TRT*Age,data=r_Data))
```


```{r}
r_data2$Sub=as.factor(rep(r_Data$Subject,5))
summary(aov(lm(bp~TRT+Visits/Sub,data=r_data2)))
```




























































